In [1]:
# [ADDED] worked example – run this cell
# Environment check – run in each environment and include the output in your report
import sys, platform, importlib
print("Python version :", sys.version.split()[0])
print("Executable     :", sys.executable)
print("Operating sys. :", platform.system(), platform.release())
for pkg in ["numpy", "pandas", "matplotlib", "sklearn", "statsmodels", "ISLP"]:
    try:
        m = importlib.import_module(pkg)
        print(f"{pkg:<12} {getattr(m, '__version__', 'installed')}")
    except ImportError:
        print(f"{pkg:<12} NOT INSTALLED – run the Setup cell / pip install ISLP")

Python version : 3.12.10
Executable     : e:\lab-statistical-learning\.venv\Scripts\python.exe
Operating sys. : Windows 11
numpy        2.5.3
pandas       2.3.3
matplotlib   3.11.2
sklearn      1.9.1
statsmodels  0.15.0
ISLP         0.4.1


In [ ]:
# ✍️ Task 0 – environment check in two environments – your code
# Write your code below (replace the TODOs), then run the cell (Shift+Enter).
full_name = "Lê Thái Đức Tùng"     # <- replace with your full name
print(f"Hello, {full_name}! My statistical-learning environment works.")


Hello, Lê Thái Đức Tùng! My statistical-learning environment works.


In [3]:
# "Restart session", accept, then run this cell once more.
import sys, os, subprocess, importlib.util, urllib.request

def ensure(module, pip_name=None):
    """pip-install a package only if it cannot be imported yet."""
    if importlib.util.find_spec(module) is None:
        print(f"Installing {pip_name or module} ...")
        subprocess.run([sys.executable, "-m", "pip", "install", "-q", pip_name or module], check=True)

ensure("ISLP", "ISLP")

# data files used by this lab (downloaded from the official ISLP_labs repository if missing)
BASE_URL = "https://raw.githubusercontent.com/intro-stat-learning/ISLP_labs/v2.2.3/"
for fname in ['Auto.csv', 'Auto.data']:
    if not os.path.exists(fname):
        os.makedirs(os.path.dirname(fname) or ".", exist_ok=True)
        urllib.request.urlretrieve(BASE_URL + fname, fname)

print("Setup complete – Python", sys.version.split()[0])


Setup complete – Python 3.12.10


In [6]:
import numpy as np

# <span style="color:red">5. Exercises</span>

<span style="color:red">Solve the exercises in the ✍️ cells of the notebook. For every exercise write **code + output + 1–3 sentences of interpretation**. Exercises 1–7 are compulsory; 8–9 are challenge (bonus) exercises.</span>

## <span style="color:red">Exercise 1 – NumPy warm-up</span>

- <span style="color:red">**(a)** Create the vector $v = (2, 4, 6, \dots, 40)$ with `np.arange()` and reshape it into a $4\times5$ matrix `M`.</span>
- <span style="color:red">**(b)** Print `M.shape`, `M.ndim`, `M.dtype` and the transpose `M.T`.</span>
- <span style="color:red">**(c)** Extract the second row, the last column and the sub-matrix of rows 2–3 and columns 1–3 (1-based counting) using slices.</span>
- <span style="color:red">**(d)** Compute row means and column standard deviations with the `axis` argument.</span>
- <span style="color:red">**(e)** Set `B = M[:2, :2]`, then `B[0, 0] = -1`. Did `M` change? Repeat with `B = M[:2, :2].copy()` and explain the difference.</span>

In [44]:
# ✍️ Exercise 1 – your code
# Write your code below (replace the TODOs), then run the cell (Shift+Enter).
import numpy as np
v = np.arange(2, 42, 2)          # TODO (a): np.arange(...)
M = v.reshape(4, 5)              # TODO (a): v.reshape(...)

In [34]:
M

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [ ]:
if M is not None:
    print(M.shape, M.ndim, M.dtype)   # (b)
    # TODO (c)–(e)
    # (c)
    print("Second row:", M[1, :])
    print("Last column:", M[:,-1])
    print("Submatrix 2-3 x 1-3:\n", M[1:3,0:3])


(4, 5) 2 int64
Second row: [12 14 16 18 20]
Last column: [10 20 30 40]
Submatrix 2-3 x 1-3:
 [[12 14 16]
 [22 24 26]]


In [ ]:
if M is not None:
    # (d)
    print(np.mean(M, axis=1))
    print(np.std(M, axis=0))

[ 6. 16. 26. 36.]
[11.18033989 11.18033989 11.18033989 11.18033989 11.18033989]


In [46]:
# (e)
v = np.arange(2, 42, 2)          # TODO (a): np.arange(...)
M = v.reshape(4, 5)              # TODO (a): v.reshape(...)
B = M[:2, :2]
B[0, 0] = -1

print(B, "\n\n", M)

[[-1  4]
 [12 14]] 

 [[-1  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


In [47]:
v = np.arange(2, 42, 2)          # TODO (a): np.arange(...)
M = v.reshape(4, 5)              # TODO (a): v.reshape(...)
B = M[:2, :2].copy()
B[0, 0] = -1

print(B, "\n\n", M)

[[-1  4]
 [12 14]] 

 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]


## <span style="color:red">Exercise 2 – Random numbers, correlation and a saved figure</span>

- <span style="color:red">**(a)** Create `rng = np.random.default_rng(2026)` and simulate $n = 100$ values $x_i \sim N(0,1)$ and $\varepsilon_i \sim N(0, 0.5^2)$.</span>
- <span style="color:red">**(b)** Compute $y_i = 2 + 3x_i + \varepsilon_i$. What is the correlation between $x$ and $y$ (`np.corrcoef`)?</span>
- <span style="color:red">**(c)** Draw a scatter plot of $y$ against $x$ with axis labels and a title, add the true line $y = 2 + 3x$ in red, and save the figure as `ex2_scatter.png` (dpi = 150).</span>
- <span style="color:red">**(d)** Re-run the cell: are the numbers the same? What happens if you remove the seed?</span>

In [ ]:
# ✍️ Exercise 2 – your code
# Write your code below (replace the TODOs), then run the cell (Shift+Enter).
import numpy as np
from matplotlib.pyplot import subplots
rng = np.random.default_rng(2026)
x = rng.standard_normal(100)
eps = None        # TODO (a)
y = None          # TODO (b)
# TODO (b): print(np.corrcoef(x, y))
# TODO (c): fig, ax = subplots(figsize=(6, 4)); ax.scatter(...); fig.savefig("ex2_scatter.png", dpi=150)
